// <auto-generated />
using System;
using InventarioApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventarioAPI.Migrations
{
    [DbContext(typeof(InventarioDbContext))]
    [Migration("20250911020852_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("InventarioApi.Models.ItemConferido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ConferidoPorId")
                        .HasColumnType("int")
                        .HasColumnName("conferido_por_id");

                    b.Property<DateTime>("DataHoraConferencia")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_hora_conferencia");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("foto_url");

                    b.Property<string>("IdentificacaoNI")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("identificacao_ni");

                    b.Property<string>("LeituraTipo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("leitura_tipo");

                    b.Property<int>("LocalEncontradoId")
                        .HasColumnType("int")
                        .HasColumnName("local_encontrado_id");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("observacao");

                    b.Property<int?>("PatrimonioId")
                        .HasColumnType("int")
                        .HasColumnName("patrimonio_id");

                    b.Property<string>("PatrimonioNome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("patrimonio_nome");

                    b.Property<bool>("PlacaIdentificacaoOk")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("placa_identificacao_ok");

                    b.Property<int>("SessaoId")
                        .HasColumnType("int")
                        .HasColumnName("sessao_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ConferidoPorId");

                    b.HasIndex("LocalEncontradoId");

                    b.HasIndex("PatrimonioId");

                    b.HasIndex("SessaoId");

                    b.ToTable("itensconferidos");
                });

            modelBuilder.Entity("InventarioApi.Models.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodigoLocal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("codigo_local");

                    b.Property<string>("NomeLocal")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome_local");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("int")
                        .HasColumnName("responsavel_id");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("locais");
                });

            modelBuilder.Entity("InventarioApi.Models.Patrimonio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescricaoEquipamento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descricao_equipamento");

                    b.Property<int?>("LocalId")
                        .HasColumnType("int")
                        .HasColumnName("local_id");

                    b.Property<string>("NumeroPatrimonio")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("numero_patrimonio");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.ToTable("patrimonios");
                });

            modelBuilder.Entity("InventarioApi.Models.SessaoConferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_inicio");

                    b.Property<int?>("IniciadaPorId")
                        .HasColumnType("int")
                        .HasColumnName("iniciada_por");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("IniciadaPorId");

                    b.ToTable("sessoesconferencia");
                });

            modelBuilder.Entity("InventarioApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome_completo");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome_usuario");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("InventarioApi.Models.ItemConferido", b =>
                {
                    b.HasOne("InventarioApi.Models.Usuario", "ConferidoPor")
                        .WithMany()
                        .HasForeignKey("ConferidoPorId");

                    b.HasOne("InventarioApi.Models.Local", "LocalEncontrado")
                        .WithMany("ItensConferidos")
                        .HasForeignKey("LocalEncontradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventarioApi.Models.Patrimonio", "Patrimonio")
                        .WithMany("ItensConferidos")
                        .HasForeignKey("PatrimonioId");

                    b.HasOne("InventarioApi.Models.SessaoConferencia", "SessaoConferencia")
                        .WithMany("ItensConferidos")
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConferidoPor");

                    b.Navigation("LocalEncontrado");

                    b.Navigation("Patrimonio");

                    b.Navigation("SessaoConferencia");
                });

            modelBuilder.Entity("InventarioApi.Models.Local", b =>
                {
                    b.HasOne("InventarioApi.Models.Usuario", "Responsavel")
                        .WithMany("LocaisResponsaveis")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("InventarioApi.Models.Patrimonio", b =>
                {
                    b.HasOne("InventarioApi.Models.Local", "Local")
                        .WithMany("Patrimonios")
                        .HasForeignKey("LocalId");

                    b.Navigation("Local");
                });

            modelBuilder.Entity("InventarioApi.Models.SessaoConferencia", b =>
                {
                    b.HasOne("InventarioApi.Models.Usuario", "IniciadaPor")
                        .WithMany("SessoesConferencia")
                        .HasForeignKey("IniciadaPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IniciadaPor");
                });

            modelBuilder.Entity("InventarioApi.Models.Local", b =>
                {
                    b.Navigation("ItensConferidos");

                    b.Navigation("Patrimonios");
                });

            modelBuilder.Entity("InventarioApi.Models.Patrimonio", b =>
                {
                    b.Navigation("ItensConferidos");
                });

            modelBuilder.Entity("InventarioApi.Models.SessaoConferencia", b =>
                {
                    b.Navigation("ItensConferidos");
                });

            modelBuilder.Entity("InventarioApi.Models.Usuario", b =>
                {
                    b.Navigation("LocaisResponsaveis");

                    b.Navigation("SessoesConferencia");
                });
#pragma warning restore 612, 618
        }
    }
}
